name = "UnivariateUnimodalHighestDensityRegion"
uuid = "accfcff7-0a28-4262-8a91-e6d956268142"
authors = ["JoelTrent <79883375+JoelTrent@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[extensions]
UnivariateUnimodalHighestDensityRegionExt = "Optimization"

[compat]
Distributions = "0.25"
StaticArrays = "1"
julia = "1.6"

[extras]
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationNLopt = "4e6fcdb7-1186-4e1f-a706-475e75c168bb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Optimization", "OptimizationNLopt", "Test"]
